name: Commit Message Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      # downloads the repository source code onto the GitHub Actions runner. 

      - name: Validate Commit Messages
        uses: wagoid/commitlint-github-action@v6  #Action to ensure Commit standards.





# *****  Branch validation check ********* 

name: Branch Policy Check    # feature/* → develop and release/* → main.

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source and target branch
        run: |
          SOURCE=${{ github.head_ref }}
          TARGET=${{ github.base_ref }}

          echo "Source Branch: $SOURCE"
          echo "Target Branch: $TARGET"

          if [[ "$SOURCE" =~ ^feature/ ]] && [[ "$TARGET" == "develop" ]]; then
            echo "Valid PR"
          else
            echo "Invalid Branch Mapping"
            exit 1
          fi
``
# ******** PR title validation ********* 

name: PR Title Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# ******** Linting Stage ******** 
# static code analysis stage executed during a PR
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci

      - uses: wearerequired/lint-action@v3   
        with:
          eslint: true
          prettier: true




#  ****** SAST CodeQL Validation *******


name: CodeQL

on:
  pull_request:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3  # Downloads codeQl CLI, Language configuration (eg java)
        with:
          languages: javascript

      #- name: Autobuild
       # uses: github/codeql-action/autobuild@v3 # 

      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3 # Runs security queries and uploads results as code scanning alerts





# ***** Secret Scanning **********

name: Secret Scan

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetches full Git history.

      - uses: gitleaks/gitleaks-action@v3  # gitleak detect hardcoded secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #other parameters need




# ***** Package creaation - creating deployables ****** 

jobs:
  build-package:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4 # eg java 

    - name: Build Package
      run: mvn clean package  # using maven as build tool 

    - name: Upload Artifact
      uses: actions/upload-artifact@v4 
      with:
        name: application
        path: target/*.jar


# ***** Deploy Job ***** 

deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:

    - name: Download Artifact
      uses: actions/download-artifact@v4

      with:
        name: app-package
        path: ./artifact

    - name: Verify Package
      run: ls -la ./artifact
``
# Eg deploying to kubernetes
#- name: Deploy to EKS
#  run: |
 #     kubectl apply -f k8s/



