name: API Test

on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request
        id: api_call
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_URL }}
          method: GET

      - name: Print Response
        run: |
          echo "Status Code: ${{ steps.api_call.outputs.status }}"
          echo "Response:"
          echo '${{ steps.api_call.outputs.response }}'
